# version: '3.8'

# services:
#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     networks:
#       - zinad-net

#   backend:
#     build: ./backend
#     ports:
#       - "5000:5000"
#     environment:
#       - FLASK_DEBUG=1  # Enable debug mode
#     networks:
#       - zinad-net

# networks:
#   zinad-net:
#     driver: bridge
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
